마이페이지 스터디 탈퇴, 삭제 Modal
LM-channel-team-project/wooggooms pull request #56
Opened 2021-06-16 07:27 UTC by 42KIM

- views/includes/mypage/modal.ejs 에서 마이페이지 상의 모달 함께 관리 (추후 가능할 시 템플릿 화?)

- 실제 스터디그룹 리스트와 미연결 상태 (그냥 모달만 있음)

- [탈퇴], [삭제] 모달창을 열고 닫을 때 각각 따로 함수를 만들어서 했는데 혹시 하나의 함수로 전부 처리할 방법이 있을지?

- 현재 모달창의 [아니오] 버튼을 눌렀을 때만 모달이 닫히도록 의도해둔 상태 (뒷 배경 클릭 등으로 창 닫기 불가) 

- 브라우저 크기 조절시 모달창이 파괴(?) 되는 상태. CSS 필요.

2021-06-16 11:13 UTC, sanoopark requested changes

2021-06-16 11:13 UTC, sanoopark commented on public/js/mypage.js
> +
> [탈퇴], [삭제] 모달창을 열고 닫을 때 각각 따로 함수를 만들어서 했는데 혹시 하나의 함수로 전부 처리할 방법이 있을지?

저는 이렇게 해봤습니다. 한 번 고려해주시면 감사하겠습니다.

```javascript
function openModal(item) {
  item.classList.add('show-modal');
}

function closeModal(item) {
  item.classList.remove('show-modal');
}
```

2021-06-16 11:13 UTC, sanoopark commented on public/js/mypage.js
> +    });
> [탈퇴], [삭제] 모달창을 열고 닫을 때 각각 따로 함수를 만들어서 했는데 혹시 하나의 함수로 전부 처리할 방법이 있을지?

저는 이렇게 해봤습니다. 한 번 고려해주시면 감사하겠습니다.

```javascript
function init() {
  myinfo_btn.addEventListener('click', redirectEditPage);

  quit_btn.forEach(Item => {
    Item.addEventListener('click', () => openModal(quit_modal));
  });

  quit_no_btn.forEach(Item => {
    Item.addEventListener('click', () => closeModal(quit_modal));
  });

  del_btn.forEach(Item => {
    Item.addEventListener('click', () => openModal(del_modal));
  });

  del_no_btn.forEach(Item => {
    Item.addEventListener('click', () => closeModal(del_modal));
  });
}
```

2021-06-16 11:48 UTC, 42KIM commented on public/js/mypage.js
> +
반영해서 수정해봤습니다!!

2021-06-16 11:59 UTC, 42KIM reviewed
상우님 피드백 반영해서 1차 수정

2021-06-16 11:59 UTC, 42KIM commented on public/js/mypage.js
> +
3연속 parentNode -> closest 로 변경

2021-06-16 11:59 UTC, 42KIM commented on public/js/mypage.js
> +    });
openModal 함수에 인자로 quit_modal과 del_modal 주는 방식으로 변경

2021-06-16 21:50 UTC, sanoopark requested changes

2021-06-16 21:50 UTC, sanoopark commented on public/js/mypage.js
> +
```javascript
function closeModal() {
  const cur_modal = this.closest('.show-modal');
  cur_modal.classList.remove('show-modal');
}
```

쓰신 방법을 보고 생각났는데 이렇게도 가능하네요!

2021-06-18 05:22 UTC, young961027 approved these changes
확인했습니다! closest 문법은 처음 보는 문법이어서 따로 더 공부해보겠습니다!

2021-07-18 09:33 UTC, 42KIM commented
상우님이 말씀해주신 ```this``` 관련하여
"원래 일반 함수로 호출되는 함수 내부의 this는 전역 객체인 window를 가리킨다. 그리고 메서드 내부에서의 this는 메서드를 호출한 객체를 가리킨다. 그러나 ```이벤트 핸들러 내부의 this```는 일반 함수처럼 window 객체를 가리키는 것이 아니라, 이벤트가 발생한 DOM 요소를 가리킨다고 한다"

2021-07-18 09:44 UTC, sanoopark approved these changes

2021-07-18 11:40 UTC, merged